import math 

functions = {
	'hypot': lambda x: math.hypot(x), 
	'ceil': lambda x: math.ceil(x), 
	'factorial': lambda x: math.factorial(x), 
	'cosh': lambda x: math.cosh(x), 
	'isnan': lambda x: math.isnan(x), 
	'erf': lambda x: math.erf(x), 
	'asin': lambda x: math.asin(x), 
	'modf': lambda x: math.modf(x), 
	'pow': lambda x: math.pow(x), 
	'isclose': lambda x: math.isclose(x), 
	'sqrt': lambda x: math.sqrt(x), 
	'atanh': lambda x: math.atanh(x), 
	'gcd': lambda x: math.gcd(x), 
	'sin': lambda x: math.sin(x), 
	'exp': lambda x: math.exp(x), 
	'lgamma': lambda x: math.lgamma(x), 
	'cos': lambda x: math.cos(x), 
	'expm1': lambda x: math.expm1(x), 
	'log1p': lambda x: math.log1p(x), 
	'gamma': lambda x: math.gamma(x), 
	'floor': lambda x: math.floor(x), 
	'frexp': lambda x: math.frexp(x), 
	'log10': lambda x: math.log10(x), 
	'trunc': lambda x: math.trunc(x), 
	'erfc': lambda x: math.erfc(x), 
	'tan': lambda x: math.tan(x), 
	'asinh': lambda x: math.asinh(x), 
	'log': lambda x: math.log(x), 
	'fabs': lambda x: math.fabs(x), 
	'radians': lambda x: math.radians(x), 
	'tanh': lambda x: math.tanh(x), 
	'isfinite': lambda x: math.isfinite(x), 
	'atan': lambda x: math.atan(x), 
	'acos': lambda x: math.acos(x), 
	'fmod': lambda x: math.fmod(x), 
	'atan2': lambda x: math.atan2(x), 
	'log2': lambda x: math.log2(x), 
	'isinf': lambda x: math.isinf(x), 
	'degrees': lambda x: math.degrees(x), 
	'sinh': lambda x: math.sinh(x), 
	'copysign': lambda x: math.copysign(x), 
	'ldexp': lambda x: math.ldexp(x), 
	'fsum': lambda x: math.fsum(x), 
	'acosh': lambda x: math.acosh(x)
}